apiVersion: apps/v1
kind: Deployment
metadata:
  name: sws-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws-app
  template:
    metadata:
      labels:
        app: sws-app
    spec:
      containers:
        - name: simple-web-server
          image: "ghcr.io/yvhaa/simple-web-service:35182a02ab39e841104257f7490d1d6c43d7bfeb"
      ports:
        containerPort: 8090
        protocol: TCP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: sws-app
#  namespace: default
#spec:
#  #type: NodePort
#  selector:
#    app: sws-app
#  ports:
#    - port: 8090
       #targetPort: 8090
