name: Build and Push Image
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Image Name
        id: get-image-name
        run: |
          CUR_TIME="$(date +%s)"
          IMAGE_NAME="ghcr.io/yvhaa/simple-web-service:x${CUR_TIME}"
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image]
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./deploy/container/Dockerfile
          tags: ${{ steps.get-image-name.outputs.image_name }}
